trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: a4789e5d-f6e8-431f-add9-379d640a883c@0
  inputs:
    terraformVersion: '0.12.24'

- script: |
     cp .provider/* .
     terraform init
  displayName: Terraform Init

- script: |
     terraform validate
  displayName: Terraform Validate
